### PR TITLE
Add KabyLake firmware.

### PR DESCRIPTION
**Pull request by daniloegea**
Add firmware for Kabylake family. Inspired by #151 
Not sure if it's working but it's loading at least:

[drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[drm] Driver supports precise vblank timestamp query.
[drm] Finished loading i915/kbl_dmc_ver1_01.bin (v1.1)
[drm] Connector eDP-1: get mode from tunables:
[drm]   - kern.vt.fb.modes.eDP-1
[drm]   - kern.vt.fb.default_mode
[drm] Connector HDMI-A-1: get mode from tunables:
[drm]   - kern.vt.fb.modes.HDMI-A-1
[drm]   - kern.vt.fb.default_mode
[drm] Connector DP-1: get mode from tunables:
[drm]   - kern.vt.fb.modes.DP-1
[drm]   - kern.vt.fb.default_mode
[drm] GuC firmware load skipped
[drm:i915_setup_sysfs] RC6 residency sysfs setup failed
[drm] Initialized i915 1.6.0 20160919 for drmn on minor 0
linux_pci_find failed!

### CODE REVIEW

**Comment by pewright-tronc** [comment]
hrm, i'm able to get it to load on my system looks like similar error i'm getting in #151 :

```
$ sudo dmesg|egrep -i dmc||guc
[drm:intel_csr_ucode_init] Loading i915/kbl_dmc_ver1_01.bin
i915/kbl_dmc_ver1_01.bin: could not load firmware image, error 2
i915/kbl_dmc_ver1_01.bin: could not load firmware image, error 2
drmn0: failed to load firmware image i915_kbl_dmc_ver1_01_bin
drmn0: Failed to load DMC firmware [https://01.org/linuxgraphics/intel-linux-graphics-firmwares], disabling runtime power management.
```

**Comment by daniloegea** [comment]
Hi, try to load the firmware first (dmc and guc) and i915kms after that.

**Comment by pewright-tronc** [comment]
How are you loading the i915kms and fw modules?  I have setup my rc.conf like so:

```
$ grep kld_list /etc/rc.conf
kld_list="i915_kbl_guc_ver9_14.bin i915kms if_iwm"
```
pre-pending the GuC fw module still results in an error while loading.  are you loading it via loader.conf?  oddly on my skylake system simply adding i915kms to my kld_list results in both the GuC and DMC getting loaded as expected.

**Comment by daniloegea** [comment]
I'm loading manually  :sweat_smile:

Probably some dependency declaration is missing.

**Comment by pewright-tronc** [comment]
thanks that's helpful - i'll try to reproduce on my end and report back any additional info i dig up.

**Comment by pewright-tronc** [comment]
so yea, manually loading modules before i915kms and I'm still unable to load the GuC blob (with same error message).  DMC loads - regardless if i manually load it or if i load i915kms first which will pull in DMC.  not sure i know a good method to debug GuC not loading, so any pointers would be helpful!

**Pull request merged**
